from peewee import CharField, ForeignKeyField, SmallIntegerField, DecimalField, DateTimeField
from playhouse.postgres_ext import JSONField
from peewee_extra_fields import EnumField

from . import BaseModel


class AlphaOwner(BaseModel):
    name = CharField()
    email = CharField()

    class Meta:
        indexes = (
            (('name', 'email'), True)
        )

class Alpha(BaseModel):
    name = CharField(unique=True)
    owner = ForeignKeyField(AlphaOwner, backref='alphas')

class Strategy(BaseModel):
    alpha = ForeignKeyField(Alpha, backref='strategies')
    rule = SmallIntegerField()
    param = SmallIntegerField()

    class Meta:
        indexes = (
            (('alpha', 'rule'), True)
        )

class Stats(BaseModel):
    strategy = ForeignKeyField(Strategy, backref='stats')
    max_dd = DecimalField(decimal_places=2, auto_round=True, default=0)
    beta = DecimalField(decimal_places=2, auto_round=True, default=0)
    vol = DecimalField(decimal_places=2, auto_round=True, default=0)
    treynor = DecimalField(decimal_places=2, auto_round=True, default=0)
    sharpe_ratio = DecimalField(decimal_places=2, auto_round=True, default=0)
    ir = DecimalField(decimal_places=2, auto_round=True, default=0)
    modigliani = DecimalField(decimal_places=2, auto_round=True, default=0)
    var = DecimalField(decimal_places=2, auto_round=True, default=0)
    cvar = DecimalField(decimal_places=2, auto_round=True, default=0)
    excess_var = DecimalField(decimal_places=2, auto_round=True, default=0)
    conditional_sharpe = DecimalField(decimal_places=2, auto_round=True, default=0)
    omega_ratio = DecimalField(decimal_places=2, auto_round=True, default=0)
    sortino = DecimalField(decimal_places=2, auto_round=True, default=0)
    kappa_three = DecimalField(decimal_places=2, auto_round=True, default=0)
    gain_loss = DecimalField(decimal_places=2, auto_round=True, default=0)
    upside_potential = DecimalField(decimal_places=2, auto_round=True, default=0)
    calmar = DecimalField(decimal_places=2, auto_round=True, default=0)
    average_dd = DecimalField(decimal_places=2, auto_round=True, default=0)
    average_dd_squared = DecimalField(decimal_places=2, auto_round=True, default=0)
    sterling_ration = DecimalField(decimal_places=2, auto_round=True, default=0)
    burke_ratio = DecimalField(decimal_places=2, auto_round=True, default=0)
    average_month_return = DecimalField(decimal_places=2, auto_round=True, default=0)
    average_trades_month = DecimalField(decimal_places=2, auto_round=True, default=0)
    trade_count = DecimalField(decimal_places=2, auto_round=True, default=0)
    alpha = DecimalField(decimal_places=2, auto_round=True, default=0)
    average_trade = DecimalField(decimal_places=2, auto_round=True, default=0)
    average_win = DecimalField(decimal_places=2, auto_round=True, default=0)
    average_loss = DecimalField(decimal_places=2, auto_round=True, default=0)
    total_wins = DecimalField(decimal_places=2, auto_round=True, default=0)
    total_losses = DecimalField(decimal_places=2, auto_round=True, default=0)
    win_rate = DecimalField(decimal_places=2, auto_round=True, default=0)
    average_mae = DecimalField(decimal_places=2, auto_round=True, default=0)
    average_mfe = DecimalField(decimal_places=2, auto_round=True, default=0)
    max_mae = DecimalField(decimal_places=2, auto_round=True, default=0)
    min_mfe = DecimalField(decimal_places=2, auto_round=True, default=0)
    ulcer_index = DecimalField(decimal_places=2, auto_round=True, default=0)
    ulcer_performance_index = DecimalField(decimal_places=2, auto_round=True, default=0)
    max_dd_duration = DecimalField(decimal_places=2, auto_round=True, default=0)
    start = DateTimeField()
    end = DateTimeField()
    total_return = DecimalField(decimal_places=2, auto_round=True, default=0)
    daily_sharpe = DecimalField(decimal_places=2, auto_round=True, default=0)
    cagr = DecimalField(decimal_places=2, auto_round=True, default=0)
    mtd = DecimalField(decimal_places=2, auto_round=True, default=0)
    three_month = DecimalField(decimal_places=2, auto_round=True, default=0)
    six_month = DecimalField(decimal_places=2, auto_round=True, default=0)
    ytd = DecimalField(decimal_places=2, auto_round=True, default=0)
    three_year = DecimalField(decimal_places=2, auto_round=True, default=0)
    daily_mean = DecimalField(decimal_places=2, auto_round=True, default=0)
    daily_vol = DecimalField(decimal_places=2, auto_round=True, default=0)
    daily_skew = DecimalField(decimal_places=2, auto_round=True, default=0)
    daily_kurt = DecimalField(decimal_places=2, auto_round=True, default=0)
    best_day = DecimalField(decimal_places=2, auto_round=True, default=0)
    worst_day = DecimalField(decimal_places=2, auto_round=True, default=0)
    monthly_sharpe = DecimalField(decimal_places=2, auto_round=True, default=0)
    monthly_mean = DecimalField(decimal_places=2, auto_round=True, default=0)
    monthly_vol = DecimalField(decimal_places=2, auto_round=True, default=0)
    monthly_skew = DecimalField(decimal_places=2, auto_round=True, default=0)
    monthly_kurt = DecimalField(decimal_places=2, auto_round=True, default=0)
    best_month = DecimalField(decimal_places=2, auto_round=True, default=0)
    worst_month = DecimalField(decimal_places=2, auto_round=True, default=0)
    yearly_sharpe = DecimalField(decimal_places=2, auto_round=True, default=0)
    yearly_mean = DecimalField(decimal_places=2, auto_round=True, default=0)
    yearly_vol = DecimalField(decimal_places=2, auto_round=True, default=0)
    yearly_skew = DecimalField(decimal_places=2, auto_round=True, default=0)
    yearly_kurt = DecimalField(decimal_places=2, auto_round=True, default=0)
    worst_year = DecimalField(decimal_places=2, auto_round=True, default=0)
    avg_drawdown_days = DecimalField(decimal_places=2, auto_round=True, default=0)
    avg_up_month = DecimalField(decimal_places=2, auto_round=True, default=0)
    avg_down_month = DecimalField(decimal_places=2, auto_round=True, default=0)
    win_year_perc = DecimalField(decimal_places=2, auto_round=True, default=0)
    twelve_month_win_perc = DecimalField(decimal_places=2, auto_round=True, default=0)
    capital_utilization = JSONField()
    rolling_sharpe = JSONField()
    returns_by_month = JSONField()
    returns_by_year = JSONField()
    percentiles = JSONField()
    drawdown_probability = JSONField()
    return_probability = JSONField()
